version: '3.8'

services:
  db:
    image: postgres:15
    container_name: contato-seguro-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crud_contato_seguro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: contato-seguro-api
    restart: always
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/crud_contato_seguro?schema=public"
      PORT: 3333
      NODE_ENV: production
    depends_on:
      - db

volumes:
  postgres_data:
